<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class CreateFillShopTables extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::unprepared('INSERT INTO `catalogo_producto_category` (`id`, `name`, `slug`) VALUES
            (1, \'Electrónica\', \'electronica\'),
            (2, \'Hogar y Cocina\', \'hogar-cocina\'),
            (3, \'Libros\', \'libros\'),
            (4, \'Ropa y Accesorios\', \'ropa-accesorios\'),
            (5, \'Deportes y Aire Libre\', \'deportes-aire-libre\'),
            (6, \'Juguetes y Juegos\', \'juguetes-juegos\'),
            (7, \'Belleza y Cuidado Personal\', \'belleza-cuidado-personal\'),
            (8, \'Herramientas y Mejoras del Hogar\', \'herramientas-mejoras-hogar\'),
            (9, \'Alimentos y Bebidas\', \'alimentos-bebidas\'),
            (10, \'Salud y Bienestar\', \'salud-bienestar\');
        ');
        DB::unprepared('
        INSERT INTO `products_to_scrapping` (`category_id`, `name`, `status`, `created_at`, `updated_at`) VALUES
        (1, \'Smartphone X Pro 128GB\', \'pending\', NOW(), NOW()),
(1, \'Auriculares Inalámbricos Bluetooth\', \'pending\', NOW(), NOW()),
(1, \'Tablet 10 Pulgadas 64GB\', \'pending\', NOW(), NOW()),
(1, \'Smart TV 4K 55 Pulgadas\', \'pending\', NOW(), NOW()),
(1, \'Portátil Ultradelgado 14"\', \'pending\', NOW(), NOW()),
(1, \'Reloj Inteligente con GPS\', \'pending\', NOW(), NOW()),
(1, \'Altavoz Inteligente con Asistente\', \'pending\', NOW(), NOW()),
(1, \'Cámara Mirrorless 24MP\', \'pending\', NOW(), NOW()),
(1, \'Drone con Cámara 4K\', \'pending\', NOW(), NOW()),
(1, \'Consola de Videojuegos Última Gen\', \'pending\', NOW(), NOW()),
(1, \'Teclado Mecánico RGB\', \'pending\', NOW(), NOW()),
(1, \'Ratón Gaming 16000DPI\', \'pending\', NOW(), NOW()),
(1, \'Monitor Curvo 27"\', \'pending\', NOW(), NOW()),
(1, \'Disco Duro Externo 2TB\', \'pending\', NOW(), NOW()),
(1, \'Router WiFi 6\', \'pending\', NOW(), NOW()),
(1, \'Power Bank 20000mAh\', \'pending\', NOW(), NOW()),
(1, \'Proyector Full HD\', \'pending\', NOW(), NOW()),
(1, \'Impresora Multifunción\', \'pending\', NOW(), NOW()),
(1, \'E-reader 8GB\', \'pending\', NOW(), NOW()),
(1, \'Tarjeta Gráfica Gaming\', \'pending\', NOW(), NOW()),
(1, \'Micrófono USB para Streaming\', \'pending\', NOW(), NOW()),
(1, \'Webcam 1080p\', \'pending\', NOW(), NOW()),
(1, \'Cargador Inalámbrico 15W\', \'pending\', NOW(), NOW()),
(1, \'Adaptador USB-C a HDMI\', \'pending\', NOW(), NOW()),
(1, \'Estación de Acoplamiento para Laptop\', \'pending\', NOW(), NOW()),
(1, \'Batería Externa para Portátil\', \'pending\', NOW(), NOW()),
(1, \'Kit de Limpieza para Electrónicos\', \'pending\', NOW(), NOW()),
(1, \'Funda para Tablet con Teclado\', \'pending\', NOW(), NOW()),
(1, \'Soporte Ajustable para Monitor\', \'pending\', NOW(), NOW()),
(1, \'Hub USB 7 en 1\', \'pending\', NOW(), NOW()),

-- Hogar y Cocina (2)
(2, \'Juego de Sartenes Antiadherentes\', \'pending\', NOW(), NOW()),
(2, \'Robot Aspirador Inteligente\', \'pending\', NOW(), NOW()),
(2, \'Cafetera Programable 12 Tazas\', \'pending\', NOW(), NOW()),
(2, \'Juego de Cuchillos de Cocina\', \'pending\', NOW(), NOW()),
(2, \'Batidora de Mano 5 Velocidades\', \'pending\', NOW(), NOW()),
(2, \'Olla Instantánea 6 Qt\', \'pending\', NOW(), NOW()),
(2, \'Juego de Toallas de Baño\', \'pending\', NOW(), NOW()),
(2, \'Edredón Queen Size\', \'pending\', NOW(), NOW()),
(2, \'Juego de Sábanas 600 Hilos\', \'pending\', NOW(), NOW()),
(2, \'Almohada de Memoria\', \'pending\', NOW(), NOW()),
(2, \'Purificador de Aire con HEPA\', \'pending\', NOW(), NOW()),
(2, \'Humidificador Ultrasónico\', \'pending\', NOW(), NOW()),
(2, \'Juego de Contenedores Herméticos\', \'pending\', NOW(), NOW()),
(2, \'Licuadora de Alta Velocidad\', \'pending\', NOW(), NOW()),
(2, \'Tostadora de 4 Ranuras\', \'pending\', NOW(), NOW()),
(2, \'Microondas de 1.2 Pies Cúbicos\', \'pending\', NOW(), NOW()),
(2, \'Horno Eléctrico de Convección\', \'pending\', NOW(), NOW()),
(2, \'Máquina de Pan Multifunción\', \'pending\', NOW(), NOW()),
(2, \'Exprimidor de Cítricos\', \'pending\', NOW(), NOW()),
(2, \'Máquina de Helados\', \'pending\', NOW(), NOW()),
(2, \'Juego de Vajilla para 12\', \'pending\', NOW(), NOW()),
(2, \'Juego de Cubiertos de Acero\', \'pending\', NOW(), NOW()),
(2, \'Tabla de Cortar de Bambú\', \'pending\', NOW(), NOW()),
(2, \'Organizador de Especias\', \'pending\', NOW(), NOW()),
(2, \'Porta Utensilios de Cocina\', \'pending\', NOW(), NOW()),
(2, \'Escurridor de Platos\', \'pending\', NOW(), NOW()),
(2, \'Jarra de Agua con Filtro\', \'pending\', NOW(), NOW()),
(2, \'Termo de Acero Inoxidable\', \'pending\', NOW(), NOW()),
(2, \'Máquina de Café Espresso\', \'pending\', NOW(), NOW()),
(2, \'Hervidor Eléctrico\', \'pending\', NOW(), NOW()),

-- Libros (3)
(3, \'El Principito - Edición Aniversario\', \'pending\', NOW(), NOW()),
(3, \'Cien Años de Soledad\', \'pending\', NOW(), NOW()),
(3, \'1984 de George Orwell\', \'pending\', NOW(), NOW()),
(3, \'El Arte de la Guerra\', \'pending\', NOW(), NOW()),
(3, \'El Alquimista\', \'pending\', NOW(), NOW()),
(3, \'Harry Potter y la Piedra Filosofal\', \'pending\', NOW(), NOW()),
(3, \'El Señor de los Anillos\', \'pending\', NOW(), NOW()),
(3, \'Orgullo y Prejuicio\', \'pending\', NOW(), NOW()),
(3, \'Matar a un Ruiseñor\', \'pending\', NOW(), NOW()),
(3, \'El Código Da Vinci\', \'pending\', NOW(), NOW()),
(3, \'Los Juegos del Hambre\', \'pending\', NOW(), NOW()),
(3, \'El Hobbit\', \'pending\', NOW(), NOW()),
(3, \'Crónica de una Muerte Anunciada\', \'pending\', NOW(), NOW()),
(3, \'Rayuela\', \'pending\', NOW(), NOW()),
(3, \'Ficciones de Borges\', \'pending\', NOW(), NOW()),
(3, \'La Sombra del Viento\', \'pending\', NOW(), NOW()),
(3, \'Don Quijote de la Mancha\', \'pending\', NOW(), NOW()),
(3, \'La Odisea\', \'pending\', NOW(), NOW()),
(3, \'La Divina Comedia\', \'pending\', NOW(), NOW()),
(3, \'Romeo y Julieta\', \'pending\', NOW(), NOW()),
(3, \'Frankenstein\', \'pending\', NOW(), NOW()),
(3, \'Drácula\', \'pending\', NOW(), NOW()),
(3, \'Moby Dick\', \'pending\', NOW(), NOW()),
(3, \'Las Aventuras de Tom Sawyer\', \'pending\', NOW(), NOW()),
(3, \'Alicia en el País de las Maravillas\', \'pending\', NOW(), NOW()),
(3, \'El Retrato de Dorian Gray\', \'pending\', NOW(), NOW()),
(3, \'Rebelión en la Granja\', \'pending\', NOW(), NOW()),
(3, \'Un Mundo Feliz\', \'pending\', NOW(), NOW()),
(3, \'Fahrenheit 451\', \'pending\', NOW(), NOW()),
(3, \'El Gran Gatsby\', \'pending\', NOW(), NOW()),

-- Ropa y Accesorios (4)
(4, \'Camiseta Básica de Algodón\', \'pending\', NOW(), NOW()),
(4, \'Jeans Slim Fit\', \'pending\', NOW(), NOW()),
(4, \'Chaqueta Denim\', \'pending\', NOW(), NOW()),
(4, \'Zapatillas Deportivas\', \'pending\', NOW(), NOW()),
(4, \'Vestido de Verano\', \'pending\', NOW(), NOW()),
(4, \'Chaqueta Impermeable\', \'pending\', NOW(), NOW()),
(4, \'Sudadera con Capucha\', \'pending\', NOW(), NOW()),
(4, \'Pantalones de Chándal\', \'pending\', NOW(), NOW()),
(4, \'Zapatos Formales de Cuero\', \'pending\', NOW(), NOW()),
(4, \'Bufanda de Lana\', \'pending\', NOW(), NOW()),
(4, \'Guantes de Invierno\', \'pending\', NOW(), NOW()),
(4, \'Gorra de Béisbol\', \'pending\', NOW(), NOW()),
(4, \'Bolso de Mano\', \'pending\', NOW(), NOW()),
(4, \'Mochila Resistente al Agua\', \'pending\', NOW(), NOW()),
(4, \'Cinturón de Cuero Genuino\', \'pending\', NOW(), NOW()),
(4, \'Calcetines Deportivos\', \'pending\', NOW(), NOW()),
(4, \'Pijama de Algodón\', \'pending\', NOW(), NOW()),
(4, \'Traje de Baño\', \'pending\', NOW(), NOW()),
(4, \'Chaleco Acolchado\', \'pending\', NOW(), NOW()),
(4, \'Blusa de Seda\', \'pending\', NOW(), NOW()),
(4, \'Falda Plisada\', \'pending\', NOW(), NOW()),
(4, \'Corbata de Seda\', \'pending\', NOW(), NOW()),
(4, \'Pantalones Cortos Deportivos\', \'pending\', NOW(), NOW()),
(4, \'Top Deportivo\', \'pending\', NOW(), NOW()),
(4, \'Leggings de Yoga\', \'pending\', NOW(), NOW()),
(4, \'Chaqueta de Cuero\', \'pending\', NOW(), NOW()),
(4, \'Abrigo de Invierno\', \'pending\', NOW(), NOW()),
(4, \'Vestido de Noche\', \'pending\', NOW(), NOW()),
(4, \'Sandalias de Playa\', \'pending\', NOW(), NOW()),
(4, \'Zapatillas de Casa\', \'pending\', NOW(), NOW()),

-- Deportes y Aire Libre (5)
(5, \'Bicicleta de Montaña\', \'pending\', NOW(), NOW()),
(5, \'Tienda de Campaña 4 Personas\', \'pending\', NOW(), NOW()),
(5, \'Mochila de Senderismo 50L\', \'pending\', NOW(), NOW()),
(5, \'Saco de Dormir 0°C\', \'pending\', NOW(), NOW()),
(5, \'Colchoneta Aislante\', \'pending\', NOW(), NOW()),
(5, \'Linterna Frontal\', \'pending\', NOW(), NOW()),
(5, \'Kit de Supervivencia\', \'pending\', NOW(), NOW()),
(5, \'Raqueta de Tenis\', \'pending\', NOW(), NOW()),
(5, \'Balón de Fútbol\', \'pending\', NOW(), NOW()),
(5, \'Balón de Baloncesto\', \'pending\', NOW(), NOW()),
(5, \'Pesas Ajustables\', \'pending\', NOW(), NOW()),
(5, \'Cinta para Correr Plegable\', \'pending\', NOW(), NOW()),
(5, \'Bicicleta Estática\', \'pending\', NOW(), NOW()),
(5, \'Mancuernas de Neopreno\', \'pending\', NOW(), NOW()),
(5, \'Colchoneta de Yoga\', \'pending\', NOW(), NOW()),
(5, \'Cuerda para Saltar\', \'pending\', NOW(), NOW()),
(5, \'Reloj Deportivo con GPS\', \'pending\', NOW(), NOW()),
(5, \'Gafas de Natación\', \'pending\', NOW(), NOW()),
(5, \'Aletas de Buceo\', \'pending\', NOW(), NOW()),
(5, \'Tabla de Surf\', \'pending\', NOW(), NOW()),
(5, \'Patines en Línea\', \'pending\', NOW(), NOW()),
(5, \'Palo de Senderismo\', \'pending\', NOW(), NOW()),
(5, \'Cantimplora de Acero\', \'pending\', NOW(), NOW()),
(5, \'Botas de Senderismo\', \'pending\', NOW(), NOW()),
(5, \'Chaqueta Impermeable\', \'pending\', NOW(), NOW()),
(5, \'Guantes de Ciclismo\', \'pending\', NOW(), NOW()),
(5, \'Casco para Bicicleta\', \'pending\', NOW(), NOW()),
(5, \'Red de Voleibol\', \'pending\', NOW(), NOW()),
(5, \'Set de Golf\', \'pending\', NOW(), NOW()),
(5, \'Pelotas de Golf\', \'pending\', NOW(), NOW()),

-- Juguetes y Juegos (6)
(6, \'Lego Classic 1500 Piezas\', \'pending\', NOW(), NOW()),
(6, \'Muñeca Articulada\', \'pending\', NOW(), NOW()),
(6, \'Set de Construcción Magnético\', \'pending\', NOW(), NOW()),
(6, \'Puzzle 1000 Piezas\', \'pending\', NOW(), NOW()),
(6, \'Juego de Mesa Familiar\', \'pending\', NOW(), NOW()),
(6, \'Figura de Acción Coleccionable\', \'pending\', NOW(), NOW()),
(6, \'Kit de Experimentos Científicos\', \'pending\', NOW(), NOW()),
(6, \'Robot Programable\', \'pending\', NOW(), NOW()),
(6, \'Juego de Química para Niños\', \'pending\', NOW(), NOW()),
(6, \'Telescopio para Principiantes\', \'pending\', NOW(), NOW()),
(6, \'Kit de Manualidades\', \'pending\', NOW(), NOW()),
(6, \'Pizarra Mágica\', \'pending\', NOW(), NOW()),
(6, \'Juego de Cocina para Niños\', \'pending\', NOW(), NOW()),
(6, \'Tren Eléctrico\', \'pending\', NOW(), NOW()),
(6, \'Coche Teledirigido\', \'pending\', NOW(), NOW()),
(6, \'Dron para Niños\', \'pending\', NOW(), NOW()),
(6, \'Juego de Construcción de Madera\', \'pending\', NOW(), NOW()),
(6, \'Muñeco de Peluche Gigante\', \'pending\', NOW(), NOW()),
(6, \'Kit de Magia\', \'pending\', NOW(), NOW()),
(6, \'Juego de Memoria\', \'pending\', NOW(), NOW()),
(6, \'Dominó de Madera\', \'pending\', NOW(), NOW()),
(6, \'Juego de Cartas Educativas\', \'pending\', NOW(), NOW()),
(6, \'Balancín para Bebés\', \'pending\', NOW(), NOW()),
(6, \'Triciclo Infantil\', \'pending\', NOW(), NOW()),
(6, \'Patín del Diablo\', \'pending\', NOW(), NOW()),
(6, \'Juego de Bolos Infantil\', \'pending\', NOW(), NOW()),
(6, \'Casa de Muñecas\', \'pending\', NOW(), NOW()),
(6, \'Kit de Pintura para Niños\', \'pending\', NOW(), NOW()),
(6, \'Juego de Herramientas de Juguete\', \'pending\', NOW(), NOW()),
(6, \'Pelota Saltarina\', \'pending\', NOW(), NOW()),

-- Belleza y Cuidado Personal (7)
(7, \'Kit de Maquillaje Profesional\', \'pending\', NOW(), NOW()),
(7, \'Secador de Pelo Iónico\', \'pending\', NOW(), NOW()),
(7, \'Plancha para el Cabello\', \'pending\', NOW(), NOW()),
(7, \'Rizador de Pestañas\', \'pending\', NOW(), NOW()),
(7, \'Depiladora Eléctrica\', \'pending\', NOW(), NOW()),
(7, \'Cepillo Limpiador Facial\', \'pending\', NOW(), NOW()),
(7, \'Serum de Vitamina C\', \'pending\', NOW(), NOW()),
(7, \'Crema Hidratante Facial\', \'pending\', NOW(), NOW()),
(7, \'Protector Solar SPF 50\', \'pending\', NOW(), NOW()),
(7, \'Kit de Cepillos de Maquillaje\', \'pending\', NOW(), NOW()),
(7, \'Perfume de Larga Duración\', \'pending\', NOW(), NOW()),
(7, \'Laca para el Cabello\', \'pending\', NOW(), NOW()),
(7, \'Gel de Ducha Hidratante\', \'pending\', NOW(), NOW()),
(7, \'Champú para Cabello Seco\', \'pending\', NOW(), NOW()),
(7, \'Acondicionador Reparador\', \'pending\', NOW(), NOW()),
(7, \'Mascarilla Capilar\', \'pending\', NOW(), NOW()),
(7, \'Aceite Esencial de Lavanda\', \'pending\', NOW(), NOW()),
(7, \'Difusor de Aromaterapia\', \'pending\', NOW(), NOW()),
(7, \'Kit de Manicura\', \'pending\', NOW(), NOW()),
(7, \'Esmalte de Uñas Larga Duración\', \'pending\', NOW(), NOW()),
(7, \'Crema para Manos\', \'pending\', NOW(), NOW()),
(7, \'Exfoliante Corporal\', \'pending\', NOW(), NOW()),
(7, \'Desodorante en Barra\', \'pending\', NOW(), NOW()),
(7, \'Cera Depilatoria\', \'pending\', NOW(), NOW()),
(7, \'Kit de Viaje para Aseo\', \'pending\', NOW(), NOW()),
(7, \'Espejo de Aumento\', \'pending\', NOW(), NOW()),
(7, \'Pinzas de Depilar\', \'pending\', NOW(), NOW()),
(7, \'Cortadora de Vello Nasal\', \'pending\', NOW(), NOW()),
(7, \'Kit de Afeitado\', \'pending\', NOW(), NOW()),
(7, \'Crema para Afeitar\', \'pending\', NOW(), NOW()),

-- Herramientas y Mejoras del Hogar (8)
(8, \'Taladro Inalámbrico\', \'pending\', NOW(), NOW()),
(8, \'Juego de Destornilladores\', \'pending\', NOW(), NOW()),
(8, \'Martillo de Garra\', \'pending\', NOW(), NOW()),
(8, \'Sierra Circular\', \'pending\', NOW(), NOW()),
(8, \'Llave Inglesa Ajustable\', \'pending\', NOW(), NOW()),
(8, \'Cinta Métrica de 5m\', \'pending\', NOW(), NOW()),
(8, \'Nivel Láser\', \'pending\', NOW(), NOW()),
(8, \'Pistola de Silicona\', \'pending\', NOW(), NOW()),
(8, \'Kit de Pintura\', \'pending\', NOW(), NOW()),
(8, \'Escalera de Aluminio\', \'pending\', NOW(), NOW()),
(8, \'Caja de Herramientas\', \'pending\', NOW(), NOW()),
(8, \'Pulidora de Coche\', \'pending\', NOW(), NOW()),
(8, \'Compresor de Aire\', \'pending\', NOW(), NOW()),
(8, \'Sierra de Calar\', \'pending\', NOW(), NOW()),
(8, \'Lijadora Orbital\', \'pending\', NOW(), NOW()),
(8, \'Kit de Fontanería\', \'pending\', NOW(), NOW()),
(8, \'Detector de Metales\', \'pending\', NOW(), NOW()),
(8, \'Cortadora de Césped\', \'pending\', NOW(), NOW()),
(8, \'Manguera de Jardín\', \'pending\', NOW(), NOW()),
(8, \'Kit de Electricista\', \'pending\', NOW(), NOW()),
(8, \'Bomba de Inflar\', \'pending\', NOW(), NOW()),
(8, \'Soporte para Taladro\', \'pending\', NOW(), NOW()),
(8, \'Guantes de Trabajo\', \'pending\', NOW(), NOW()),
(8, \'Gafas de Seguridad\', \'pending\', NOW(), NOW()),
(8, \'Casco de Obra\', \'pending\', NOW(), NOW()),
(8, \'Extensión Eléctrica\', \'pending\', NOW(), NOW()),
(8, \'Organizador de Herramientas\', \'pending\', NOW(), NOW()),
(8, \'Candado de Seguridad\', \'pending\', NOW(), NOW()),
(8, \'Kit de Reparación de Bicicletas\', \'pending\', NOW(), NOW()),
(8, \'Cepillo para Limpieza\', \'pending\', NOW(), NOW()),

-- Alimentos y Bebidas (9)
(9, \'Café en Grano Premium\', \'pending\', NOW(), NOW()),
(9, \'Té Verde en Hojas Sueltas\', \'pending\', NOW(), NOW()),
(9, \'Aceite de Oliva Virgen Extra\', \'pending\', NOW(), NOW()),
(9, \'Vinagre Balsámico\', \'pending\', NOW(), NOW()),
(9, \'Miel Orgánica\', \'pending\', NOW(), NOW()),
(9, \'Chocolate Negro 85% Cacao\', \'pending\', NOW(), NOW()),
(9, \'Frutos Secos Variados\', \'pending\', NOW(), NOW()),
(9, \'Galletas Integrales\', \'pending\', NOW(), NOW()),
(9, \'Mermelada Artesanal\', \'pending\', NOW(), NOW()),
(9, \'Pasta Orgánica\', \'pending\', NOW(), NOW()),
(9, \'Arroz Basmati\', \'pending\', NOW(), NOW()),
(9, \'Quinoa Orgánica\', \'pending\', NOW(), NOW()),
(9, \'Salsa de Tomate Natural\', \'pending\', NOW(), NOW()),
(9, \'Cereales Integrales\', \'pending\', NOW(), NOW()),
(9, \'Barritas Energéticas\', \'pending\', NOW(), NOW()),
(9, \'Proteína en Polvo\', \'pending\', NOW(), NOW()),
(9, \'Suplemento Vitamínico\', \'pending\', NOW(), NOW()),
(9, \'Agua Mineral con Gas\', \'pending\', NOW(), NOW()),
(9, \'Zumo de Naranja Natural\', \'pending\', NOW(), NOW()),
(9, \'Vino Tinto Reserva\', \'pending\', NOW(), NOW()),
(9, \'Cerveza Artesanal\', \'pending\', NOW(), NOW()),
(9, \'Whisky de Malta\', \'pending\', NOW(), NOW()),
(9, \'Ron Añejo\', \'pending\', NOW(), NOW()),
(9, \'Licor de Hierbas\', \'pending\', NOW(), NOW()),
(9, \'Snacks Saludables\', \'pending\', NOW(), NOW()),
(9, \'Palomitas de Maíz\', \'pending\', NOW(), NOW()),
(9, \'Fruta Deshidratada\', \'pending\', NOW(), NOW()),
(9, \'Semillas de Chía\', \'pending\', NOW(), NOW()),
(9, \'Levadura Nutricional\', \'pending\', NOW(), NOW()),
(9, \'Especias Variadas\', \'pending\', NOW(), NOW()),

-- Salud y Bienestar (10)
(10, \'Termómetro Digital\', \'pending\', NOW(), NOW()),
(10, \'Tensiómetro de Brazo\', \'pending\', NOW(), NOW()),
(10, \'Monitor de Glucosa\', \'pending\', NOW(), NOW()),
(10, \'Báscula Digital\', \'pending\', NOW(), NOW()),
(10, \'Masajeador Eléctrico\', \'pending\', NOW(), NOW()),
(10, \'Almohada Ortopédica\', \'pending\', NOW(), NOW()),
(10, \'Colchón Viscoelástico\', \'pending\', NOW(), NOW()),
(10, \'Rodillo de Masaje\', \'pending\', NOW(), NOW()),
(10, \'Bandas de Resistencia\', \'pending\', NOW(), NOW()),
(10, \'Kit de Primeros Auxilios\', \'pending\', NOW(), NOW()),
(10, \'Humidificador de Aire\', \'pending\', NOW(), NOW()),
(10, \'Purificador de Agua\', \'pending\', NOW(), NOW()),
(10, \'Compresa Caliente\', \'pending\', NOW(), NOW()),
(10, \'Venda Elástica\', \'pending\', NOW(), NOW()),
(10, \'Muletas Ajustables\', \'pending\', NOW(), NOW()),
(10, \'Silla de Ruedas Plegable\', \'pending\', NOW(), NOW()),
(10, \'Andador para Adultos\', \'pending\', NOW(), NOW()),
(10, \'Faja Lumbar\', \'pending\', NOW(), NOW()),
(10, \'Protector Solar Facial\', \'pending\', NOW(), NOW()),
(10, \'Repelente de Insectos\', \'pending\', NOW(), NOW()),
(10, \'Suplemento de Omega 3\', \'pending\', NOW(), NOW()),
(10, \'Vitamina D3\', \'pending\', NOW(), NOW()),
(10, \'Melatonina para Dormir\', \'pending\', NOW(), NOW()),
(10, \'Probióticos Digestivos\', \'pending\', NOW(), NOW()),
(10, \'Colágeno Hidrolizado\', \'pending\', NOW(), NOW()),
(10, \'Aceite Esencial de Eucalipto\', \'pending\', NOW(), NOW()),
(10, \'Difusor Ultrasónico\', \'pending\', NOW(), NOW()),
(10, \'Almohadilla Térmica\', \'pending\', NOW(), NOW()),
(10, \'Cepillo de Dientes Eléctrico\', \'pending\', NOW(), NOW()),
(10, \'Hilo Dental\', \'pending\', NOW(), NOW());');
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('fill_shop_tables');
    }
}
